language: python
python:
  - 2.7
  - pypy
  - 3.3
install:
  - pip install -r requirements.txt -r tests/requirements.txt
script:
  - python setup.py install
  - nosetests --rednose --with-cov --cov-config=.coveragerc
after_success: codecov
